export QT_QPA_PLATFORM="wayland;xcb"
export QT_QPA_PLATFORMTHEME="qt6ct"
export QT_AUTO_SCREEN_SCALE_FACTOR=0.8
export CLUTTER_BACKEND="wayland"
export _JAVA_AWT_WM_NONREPARENTING=1
export XDG_SESSION_TYPE="wayland"
export ADW_DISABLE_PORTAL=1
export ELECTRON_OZONE_PLATFORM_HINT="auto"

